import * as fs from 'fs';
import * as path from 'path';
import { ReviewResult, ReviewIssue, OutputOptions } from '../types';
import { logger } from '../utils/logger';

export class Exporter {
  private options: OutputOptions;

  constructor(options: OutputOptions) {
    this.options = options;
  }

  export(result: ReviewResult): string {
    let output: string;

    switch (this.options.format) {
      case 'json':
        output = this.toJSON(result);
        break;
      case 'markdown':
        output = this.toMarkdown(result);
        break;
      case 'html':
        output = this.toHTML(result);
        break;
      case 'cli':
      default:
        return '';
    }

    if (this.options.outputFile) {
      this.saveToFile(output, this.options.outputFile);
    }

    return output;
  }

  private toJSON(result: ReviewResult): string {
    return JSON.stringify(result, null, 2);
  }

  private toMarkdown(result: ReviewResult): string {
    const lines: string[] = [];

    lines.push('# PR Review Report');
    lines.push('');
    lines.push(`**Generated:** ${result.metadata.reviewedAt}`);
    lines.push(`**Model:** ${result.metadata.model}`);
    lines.push(`**Duration:** ${(result.metadata.duration / 1000).toFixed(2)}s`);
    lines.push('');

    lines.push('## Summary');
    lines.push('');
    lines.push(result.summary);
    lines.push('');

    lines.push('## Statistics');
    lines.push('');
    lines.push(`| Severity | Count |`);
    lines.push(`|----------|-------|`);
    lines.push(`| 🔴 Critical | ${result.stats.critical} |`);
    lines.push(`| 🟠 High | ${result.stats.high} |`);
    lines.push(`| 🟡 Medium | ${result.stats.medium} |`);
    lines.push(`| 🔵 Low | ${result.stats.low} |`);
    lines.push(`| **Total** | **${result.stats.totalIssues}** |`);
    lines.push('');

    if (result.issues.length > 0) {
      lines.push('## Issues');
      lines.push('');

      const grouped = this.groupIssues(result.issues);

      for (const [group, issues] of Object.entries(grouped)) {
        lines.push(`### ${group}`);
        lines.push('');

        for (const issue of issues) {
          const severity = this.getSeverityEmoji(issue.severity);
          const location = issue.line ? `:${issue.line}` : '';
          
          lines.push(`#### ${severity} ${issue.category.toUpperCase()}`);
          lines.push('');
          lines.push(`**File:** \`${issue.file}${location}\``);
          lines.push('');
          lines.push(`**Issue:** ${issue.message}`);
          lines.push('');
          
          if (issue.suggestion) {
            lines.push(`**Suggestion:** ${issue.suggestion}`);
            lines.push('');
          }

          if (issue.codeSnippet && this.options.includeCodeSnippets) {
            lines.push('```');
            lines.push(issue.codeSnippet);
            lines.push('```');
            lines.push('');
          }
        }
      }
    }

    lines.push('---');
    lines.push('*Generated by PR Reviewer*');

    return lines.join('\n');
  }

  private toHTML(result: ReviewResult): string {
    const severityColors: Record<string, string> = {
      critical: '#dc2626',
      high: '#ea580c',
      medium: '#ca8a04',
      low: '#2563eb',
    };

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PR Review Report</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1f2937; background: #f9fafb; padding: 2rem; }
    .container { max-width: 900px; margin: 0 auto; background: white; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); padding: 2rem; }
    h1 { color: #111827; margin-bottom: 1rem; }
    h2 { color: #374151; margin: 1.5rem 0 1rem; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5rem; }
    h3 { color: #4b5563; margin: 1rem 0 0.5rem; }
    .meta { color: #6b7280; font-size: 0.875rem; margin-bottom: 1.5rem; }
    .summary { background: #f3f4f6; padding: 1rem; border-radius: 8px; margin-bottom: 1.5rem; }
    .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 1rem; margin-bottom: 1.5rem; }
    .stat { background: #f9fafb; padding: 1rem; border-radius: 8px; text-align: center; border: 1px solid #e5e7eb; }
    .stat-value { font-size: 2rem; font-weight: bold; }
    .stat-label { font-size: 0.75rem; color: #6b7280; text-transform: uppercase; }
    .issue { border: 1px solid #e5e7eb; border-radius: 8px; padding: 1rem; margin-bottom: 1rem; border-left: 4px solid; }
    .issue-critical { border-left-color: ${severityColors.critical}; }
    .issue-high { border-left-color: ${severityColors.high}; }
    .issue-medium { border-left-color: ${severityColors.medium}; }
    .issue-low { border-left-color: ${severityColors.low}; }
    .issue-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; }
    .severity { padding: 0.25rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: 600; color: white; }
    .severity-critical { background: ${severityColors.critical}; }
    .severity-high { background: ${severityColors.high}; }
    .severity-medium { background: ${severityColors.medium}; }
    .severity-low { background: ${severityColors.low}; }
    .category { color: #6b7280; font-size: 0.875rem; }
    .file { font-family: monospace; background: #f3f4f6; padding: 0.25rem 0.5rem; border-radius: 4px; font-size: 0.875rem; }
    .message { margin: 0.5rem 0; }
    .suggestion { background: #ecfdf5; padding: 0.75rem; border-radius: 4px; margin-top: 0.5rem; color: #065f46; }
    .code { background: #1f2937; color: #f9fafb; padding: 1rem; border-radius: 4px; font-family: monospace; font-size: 0.875rem; overflow-x: auto; margin-top: 0.5rem; }
    .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 0.875rem; text-align: center; }
  </style>
</head>
<body>
  <div class="container">
    <h1>🔍 PR Review Report</h1>
    <div class="meta">
      <p>Generated: ${result.metadata.reviewedAt} | Model: ${result.metadata.model} | Duration: ${(result.metadata.duration / 1000).toFixed(2)}s</p>
      <p>Files: ${result.metadata.filesReviewed} | Lines: ${result.metadata.linesReviewed} | Chunks: ${result.metadata.chunksProcessed}</p>
    </div>

    <div class="summary">
      <strong>Summary:</strong> ${result.summary}
    </div>

    <div class="stats">
      <div class="stat">
        <div class="stat-value" style="color: ${severityColors.critical}">${result.stats.critical}</div>
        <div class="stat-label">Critical</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color: ${severityColors.high}">${result.stats.high}</div>
        <div class="stat-label">High</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color: ${severityColors.medium}">${result.stats.medium}</div>
        <div class="stat-label">Medium</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color: ${severityColors.low}">${result.stats.low}</div>
        <div class="stat-label">Low</div>
      </div>
      <div class="stat">
        <div class="stat-value">${result.stats.totalIssues}</div>
        <div class="stat-label">Total</div>
      </div>
    </div>

    ${result.issues.length > 0 ? `
    <h2>Issues</h2>
    ${result.issues.map(issue => `
      <div class="issue issue-${issue.severity}">
        <div class="issue-header">
          <span class="severity severity-${issue.severity}">${issue.severity.toUpperCase()}</span>
          <span class="category">${issue.category}</span>
        </div>
        <div class="file">${issue.file}${issue.line ? `:${issue.line}` : ''}</div>
        <p class="message">${issue.message}</p>
        ${issue.suggestion ? `<div class="suggestion">💡 ${issue.suggestion}</div>` : ''}
        ${issue.codeSnippet && this.options.includeCodeSnippets ? `<pre class="code">${this.escapeHtml(issue.codeSnippet)}</pre>` : ''}
      </div>
    `).join('')}
    ` : '<p>No issues found! 🎉</p>'}

    <div class="footer">
      Generated by PR Reviewer
    </div>
  </div>
</body>
</html>`;
  }

  private groupIssues(issues: ReviewIssue[]): Record<string, ReviewIssue[]> {
    const grouped: Record<string, ReviewIssue[]> = {};
    const groupBy = this.options.groupBy || 'file';

    for (const issue of issues) {
      let key: string;
      switch (groupBy) {
        case 'severity':
          key = issue.severity;
          break;
        case 'category':
          key = issue.category;
          break;
        case 'file':
        default:
          key = issue.file;
      }

      if (!grouped[key]) {
        grouped[key] = [];
      }
      grouped[key].push(issue);
    }

    return grouped;
  }

  private getSeverityEmoji(severity: string): string {
    switch (severity) {
      case 'critical': return '🔴';
      case 'high': return '🟠';
      case 'medium': return '🟡';
      case 'low': return '🔵';
      default: return '⚪';
    }
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }

  private saveToFile(content: string, filePath: string): void {
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(filePath, content, 'utf-8');
    logger.info(`Report saved to: ${filePath}`);
  }
}

export function createExporter(options: OutputOptions): Exporter {
  return new Exporter(options);
}
