import { useState } from 'react';
import { Download, FileJson, FileText, File, X, Check } from 'lucide-react';

interface ReviewData {
  id: string;
  summary: string;
  issues: Array<{
    file: string;
    line?: number;
    severity: string;
    category: string;
    message: string;
    suggestion?: string;
    confidence?: number;
    reasoning?: string;
  }>;
  stats: {
    totalIssues: number;
    critical: number;
    high: number;
    medium: number;
    low: number;
  };
  metadata: {
    reviewedAt: string;
    duration: number;
    model: string;
    filesReviewed: number;
    overallRiskLevel?: string;
    approvalRecommendation?: string;
    overallConfidence?: number;
  };
}

interface ExportOptionsProps {
  review: ReviewData;
  onClose?: () => void;
}

type ExportFormat = 'json' | 'markdown' | 'html';

export default function ExportOptions({ review, onClose }: ExportOptionsProps) {
  const [format, setFormat] = useState<ExportFormat>('markdown');
  const [includeMetadata, setIncludeMetadata] = useState(true);
  const [includeSuggestions, setIncludeSuggestions] = useState(true);
  const [copied, setCopied] = useState(false);

  const generateExport = (): string => {
    switch (format) {
      case 'json':
        return generateJSON();
      case 'markdown':
        return generateMarkdown();
      case 'html':
        return generateHTML();
      default:
        return '';
    }
  };

  const generateJSON = (): string => {
    const data = {
      ...review,
      exportedAt: new Date().toISOString(),
    };
    if (!includeMetadata) {
      delete (data as any).metadata;
    }
    if (!includeSuggestions) {
      data.issues = data.issues.map(i => {
        const { suggestion, ...rest } = i;
        return rest;
      });
    }
    return JSON.stringify(data, null, 2);
  };

  const generateMarkdown = (): string => {
    const lines: string[] = [];
    
    lines.push('# PR Review Report');
    lines.push('');
    
    if (includeMetadata) {
      lines.push('## Overview');
      lines.push('');
      lines.push(`- **Date:** ${new Date(review.metadata.reviewedAt).toLocaleString()}`);
      lines.push(`- **Duration:** ${(review.metadata.duration / 1000).toFixed(1)}s`);
      lines.push(`- **Files Reviewed:** ${review.metadata.filesReviewed}`);
      lines.push(`- **Risk Level:** ${review.metadata.overallRiskLevel || 'Unknown'}`);
      lines.push(`- **Recommendation:** ${review.metadata.approvalRecommendation?.replace('_', ' ') || 'Unknown'}`);
      if (review.metadata.overallConfidence) {
        lines.push(`- **Confidence:** ${review.metadata.overallConfidence}%`);
      }
      lines.push('');
    }
    
    lines.push('## Summary');
    lines.push('');
    lines.push(review.summary);
    lines.push('');
    
    lines.push('## Statistics');
    lines.push('');
    lines.push(`| Severity | Count |`);
    lines.push(`|----------|-------|`);
    lines.push(`| Critical | ${review.stats.critical} |`);
    lines.push(`| High | ${review.stats.high} |`);
    lines.push(`| Medium | ${review.stats.medium} |`);
    lines.push(`| Low | ${review.stats.low} |`);
    lines.push(`| **Total** | **${review.stats.totalIssues}** |`);
    lines.push('');
    
    lines.push('## Issues');
    lines.push('');
    
    const severityOrder = ['critical', 'high', 'medium', 'low'];
    const sortedIssues = [...review.issues].sort((a, b) => 
      severityOrder.indexOf(a.severity) - severityOrder.indexOf(b.severity)
    );
    
    for (const issue of sortedIssues) {
      const severityEmoji = {
        critical: '🔴',
        high: '🟠',
        medium: '🟡',
        low: '🔵'
      }[issue.severity] || '⚪';
      
      lines.push(`### ${severityEmoji} ${issue.severity.toUpperCase()}: ${issue.category}`);
      lines.push('');
      lines.push(`**File:** \`${issue.file}${issue.line ? `:${issue.line}` : ''}\``);
      if (issue.confidence) {
        lines.push(`**Confidence:** ${issue.confidence}%`);
      }
      lines.push('');
      lines.push(issue.message);
      lines.push('');
      
      if (includeSuggestions && issue.suggestion) {
        lines.push(`> 💡 **Suggestion:** ${issue.suggestion}`);
        lines.push('');
      }
      
      if (issue.reasoning) {
        lines.push(`> **Reasoning:** ${issue.reasoning}`);
        lines.push('');
      }
    }
    
    lines.push('---');
    lines.push(`*Generated by PR Reviewer on ${new Date().toLocaleString()}*`);
    
    return lines.join('\n');
  };

  const generateHTML = (): string => {
    const severityColors: Record<string, string> = {
      critical: '#ef4444',
      high: '#f97316',
      medium: '#eab308',
      low: '#3b82f6'
    };

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PR Review Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; background: #f9fafb; }
    h1 { color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
    h2 { color: #374151; margin-top: 30px; }
    .meta { background: #fff; padding: 15px; border-radius: 8px; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    .meta p { margin: 5px 0; color: #6b7280; }
    .summary { background: #fff; padding: 20px; border-radius: 8px; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-bottom: 20px; }
    .stat { background: #fff; padding: 15px; border-radius: 8px; text-align: center; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    .stat-value { font-size: 24px; font-weight: bold; }
    .stat-label { font-size: 12px; color: #6b7280; text-transform: uppercase; }
    .issue { background: #fff; padding: 15px; border-radius: 8px; margin-bottom: 10px; border-left: 4px solid; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    .issue-header { display: flex; align-items: center; gap: 10px; margin-bottom: 10px; }
    .severity { padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; color: white; }
    .file { font-family: monospace; font-size: 12px; color: #6b7280; }
    .message { color: #374151; }
    .suggestion { background: #f3f4f6; padding: 10px; border-radius: 4px; margin-top: 10px; font-size: 14px; color: #4b5563; }
    .footer { text-align: center; color: #9ca3af; font-size: 12px; margin-top: 30px; }
  </style>
</head>
<body>
  <h1>PR Review Report</h1>
  
  ${includeMetadata ? `
  <div class="meta">
    <p><strong>Date:</strong> ${new Date(review.metadata.reviewedAt).toLocaleString()}</p>
    <p><strong>Duration:</strong> ${(review.metadata.duration / 1000).toFixed(1)}s</p>
    <p><strong>Files Reviewed:</strong> ${review.metadata.filesReviewed}</p>
    <p><strong>Risk Level:</strong> ${review.metadata.overallRiskLevel || 'Unknown'}</p>
    <p><strong>Recommendation:</strong> ${review.metadata.approvalRecommendation?.replace('_', ' ') || 'Unknown'}</p>
    ${review.metadata.overallConfidence ? `<p><strong>Confidence:</strong> ${review.metadata.overallConfidence}%</p>` : ''}
  </div>
  ` : ''}
  
  <div class="summary">
    <h2 style="margin-top: 0;">Summary</h2>
    <p>${review.summary}</p>
  </div>
  
  <div class="stats">
    <div class="stat" style="border-top: 3px solid ${severityColors.critical}">
      <div class="stat-value">${review.stats.critical}</div>
      <div class="stat-label">Critical</div>
    </div>
    <div class="stat" style="border-top: 3px solid ${severityColors.high}">
      <div class="stat-value">${review.stats.high}</div>
      <div class="stat-label">High</div>
    </div>
    <div class="stat" style="border-top: 3px solid ${severityColors.medium}">
      <div class="stat-value">${review.stats.medium}</div>
      <div class="stat-label">Medium</div>
    </div>
    <div class="stat" style="border-top: 3px solid ${severityColors.low}">
      <div class="stat-value">${review.stats.low}</div>
      <div class="stat-label">Low</div>
    </div>
  </div>
  
  <h2>Issues (${review.stats.totalIssues})</h2>
  
  ${review.issues.map(issue => `
  <div class="issue" style="border-color: ${severityColors[issue.severity] || '#9ca3af'}">
    <div class="issue-header">
      <span class="severity" style="background: ${severityColors[issue.severity] || '#9ca3af'}">${issue.severity.toUpperCase()}</span>
      <span style="background: #e5e7eb; padding: 2px 8px; border-radius: 4px; font-size: 12px;">${issue.category}</span>
      ${issue.confidence ? `<span style="font-size: 12px; color: #6b7280;">${issue.confidence}% confidence</span>` : ''}
    </div>
    <div class="file">${issue.file}${issue.line ? `:${issue.line}` : ''}</div>
    <p class="message">${issue.message}</p>
    ${includeSuggestions && issue.suggestion ? `<div class="suggestion">💡 ${issue.suggestion}</div>` : ''}
  </div>
  `).join('')}
  
  <div class="footer">Generated by PR Reviewer on ${new Date().toLocaleString()}</div>
</body>
</html>`;
  };

  const handleDownload = () => {
    const content = generateExport();
    const mimeTypes: Record<ExportFormat, string> = {
      json: 'application/json',
      markdown: 'text/markdown',
      html: 'text/html'
    };
    const extensions: Record<ExportFormat, string> = {
      json: 'json',
      markdown: 'md',
      html: 'html'
    };
    
    const blob = new Blob([content], { type: mimeTypes[format] });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `review-${review.id || 'export'}.${extensions[format]}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    const content = generateExport();
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-4 shadow-lg">
      <div className="flex items-center justify-between mb-4">
        <h3 className="font-semibold text-gray-900 dark:text-white flex items-center gap-2">
          <Download className="w-5 h-5" />
          Export Review
        </h3>
        {onClose && (
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
            <X className="w-5 h-5" />
          </button>
        )}
      </div>

      {/* Format Selection */}
      <div className="mb-4">
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Format</label>
        <div className="flex gap-2">
          <button
            onClick={() => setFormat('json')}
            className={`flex items-center gap-2 px-3 py-2 rounded-lg text-sm ${
              format === 'json' 
                ? 'bg-primary-600 text-white' 
                : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
            }`}
          >
            <FileJson className="w-4 h-4" />
            JSON
          </button>
          <button
            onClick={() => setFormat('markdown')}
            className={`flex items-center gap-2 px-3 py-2 rounded-lg text-sm ${
              format === 'markdown' 
                ? 'bg-primary-600 text-white' 
                : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
            }`}
          >
            <FileText className="w-4 h-4" />
            Markdown
          </button>
          <button
            onClick={() => setFormat('html')}
            className={`flex items-center gap-2 px-3 py-2 rounded-lg text-sm ${
              format === 'html' 
                ? 'bg-primary-600 text-white' 
                : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
            }`}
          >
            <File className="w-4 h-4" />
            HTML
          </button>
        </div>
      </div>

      {/* Options */}
      <div className="mb-4 space-y-2">
        <label className="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
          <input
            type="checkbox"
            checked={includeMetadata}
            onChange={(e) => setIncludeMetadata(e.target.checked)}
            className="rounded border-gray-300 dark:border-gray-600"
          />
          Include metadata
        </label>
        <label className="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
          <input
            type="checkbox"
            checked={includeSuggestions}
            onChange={(e) => setIncludeSuggestions(e.target.checked)}
            className="rounded border-gray-300 dark:border-gray-600"
          />
          Include suggestions
        </label>
      </div>

      {/* Actions */}
      <div className="flex gap-2">
        <button
          onClick={handleDownload}
          className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700"
        >
          <Download className="w-4 h-4" />
          Download
        </button>
        <button
          onClick={handleCopy}
          className="flex items-center justify-center gap-2 px-4 py-2 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600"
        >
          {copied ? <Check className="w-4 h-4 text-green-500" /> : <FileText className="w-4 h-4" />}
          {copied ? 'Copied!' : 'Copy'}
        </button>
      </div>
    </div>
  );
}
